services:
  - type: worker
    name: telegram-novel-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: MONGO_URI
        fromSecret: true
      - key: BOT_OWNER
        fromSecret: true
